version: '3.8'
services:
  app:
    image: hsbc-springboot-app
    container_name: hsbc-springboot-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
# Redis and MySQL are expected to be external services accessible at host.docker.internal